/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import javax.swing.JPanel;

/**
 *
 * @author PERSONAL
 */
public class PantallaCliente extends javax.swing.JFrame {

    
    Cliente refCliente;
    String nombreTurno;
    
    public PantallaCliente() {
        initComponents();
        nombreTurno = ""; 
   }

    
    public void setCliente(Cliente refCliente){
        this.refCliente = refCliente;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHealth = new javax.swing.JLabel();
        txtConsole = new java.awt.TextArea();
        txtFieldConsole = new java.awt.TextField();
        btnSend = new javax.swing.JButton();
        txtLastPlay = new java.awt.TextArea();
        txtBitacora = new java.awt.TextArea();
        lblHero3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblHealth1 = new javax.swing.JLabel();
        lblHero1 = new javax.swing.JLabel();
        lblHero2 = new javax.swing.JLabel();
        jLabel609 = new javax.swing.JLabel();
        jLabel610 = new javax.swing.JLabel();
        lblTurn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1813, 1050));
        setPreferredSize(new java.awt.Dimension(1800, 1050));
        getContentPane().setLayout(null);

        lblHealth.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblHealth.setForeground(new java.awt.Color(0, 0, 0));
        lblHealth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHealth.setText("Casillas destroyed:");
        getContentPane().add(lblHealth);
        lblHealth.setBounds(1050, 460, 230, 30);
        getContentPane().add(txtConsole);
        txtConsole.setBounds(580, 620, 1200, 330);
        getContentPane().add(txtFieldConsole);
        txtFieldConsole.setBounds(570, 970, 1130, 20);

        btnSend.setText("Send");
        getContentPane().add(btnSend);
        btnSend.setBounds(1720, 970, 59, 25);
        getContentPane().add(txtLastPlay);
        txtLastPlay.setBounds(20, 720, 520, 260);
        getContentPane().add(txtBitacora);
        txtBitacora.setBounds(20, 70, 520, 530);

        lblHero3.setText("jLabel8");
        lblHero3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblHero3);
        lblHero3.setBounds(1420, 400, 140, 150);

        jLabel2.setToolTipText("");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(570, 610, 1220, 350);

        jLabel7.setToolTipText("");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(570, 20, 810, 440);

        lblHealth1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblHealth1.setForeground(new java.awt.Color(0, 0, 0));
        lblHealth1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHealth1.setText("Health:");
        getContentPane().add(lblHealth1);
        lblHealth1.setBounds(580, 460, 90, 30);

        lblHero1.setText("jLabel8");
        lblHero1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblHero1);
        lblHero1.setBounds(1420, 40, 140, 150);

        lblHero2.setText("jLabel8");
        lblHero2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblHero2);
        lblHero2.setBounds(1420, 220, 140, 150);

        jLabel609.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel609.setForeground(new java.awt.Color(0, 0, 0));
        jLabel609.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel609.setText("Last play");
        getContentPane().add(jLabel609);
        jLabel609.setBounds(170, 680, 180, 40);

        jLabel610.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel610.setForeground(new java.awt.Color(0, 0, 0));
        jLabel610.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel610.setText("Bitacora");
        getContentPane().add(jLabel610);
        jLabel610.setBounds(180, 30, 180, 40);

        lblTurn.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTurn.setForeground(new java.awt.Color(0, 0, 0));
        lblTurn.setText("Turn:");
        getContentPane().add(lblTurn);
        lblTurn.setBounds(30, 620, 160, 40);

        jLabel1.setToolTipText("");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 610, 540, 380);

        jLabel3.setToolTipText("");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 20, 540, 650);

        jLabel4.setToolTipText("");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(570, 20, 810, 580);

        jLabel5.setToolTipText("");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(570, 20, 810, 580);

        jLabel6.setToolTipText("");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1390, 20, 400, 580);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FondoCliente.jpg"))); // NOI18N
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, 0, 1800, 1000);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel609;
    private javax.swing.JLabel jLabel610;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblHealth;
    private javax.swing.JLabel lblHealth1;
    private javax.swing.JLabel lblHero1;
    private javax.swing.JLabel lblHero2;
    private javax.swing.JLabel lblHero3;
    private javax.swing.JLabel lblTurn;
    private java.awt.TextArea txtBitacora;
    private java.awt.TextArea txtConsole;
    private java.awt.TextField txtFieldConsole;
    private java.awt.TextArea txtLastPlay;
    // End of variables declaration//GEN-END:variables
}
