/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Server;

/**
 *
 * @author PERSONAL
 */
public class PantallaServer extends javax.swing.JFrame {

    public Server srv;
    
    public PantallaServer() {
        initComponents();
    }

    public void setServer(Server srv){
        this.srv = srv;
    }
    
    public void addMessage(String msj){
        txtStatus.append(msj + "\n");
    }
    
    public void increaseConnections(){
        String num = Integer.toString(srv.contadorDeConexiones);
        lblConectados.setText(num);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtStatus = new java.awt.TextArea();
        jLabel2 = new javax.swing.JLabel();
        lblConectados = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1140, 800));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(txtStatus);
        txtStatus.setBounds(440, 320, 310, 340);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SeaWars.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 80, 390, 211);

        lblConectados.setBackground(new java.awt.Color(0, 0, 0));
        lblConectados.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        lblConectados.setForeground(new java.awt.Color(204, 204, 0));
        lblConectados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConectados.setText("0");
        lblConectados.setOpaque(true);
        getContentPane().add(lblConectados);
        lblConectados.setBounds(840, 360, 160, 110);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setText("Players Connected:");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(840, 290, 160, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FondoServer.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1165, 800));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1140, 810);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblConectados;
    private java.awt.TextArea txtStatus;
    // End of variables declaration//GEN-END:variables
}
